branchProtectionRules:
  - pattern: main
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: true
    requiredStatusCheckContexts:
      - 'ci/kokoro: Samples test'
      - 'ci/kokoro: System test'
      - docs
      - lint
      - test (12)
      - test (14)
      - test (16)
      - cla/google
      - windows
      - OwlBot Post Processor
permissionRules:
  - team: yoshi-admins
    permission: admin
  - team: yoshi-nodejs-admins
    permission: admin
  - team: yoshi-nodejs
    permission: push
