// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

/* global window */
import * as gax from 'google-gax';
import {Callback, CallOptions, Descriptors, ClientOptions} from 'google-gax';
import * as path from 'path';

import * as protos from '../../protos/protos';
/**
 * Client JSON configuration object, loaded from
 * `src/v1/disks_client_config.json`.
 * This file defines retry strategy and timeouts for all API methods in this library.
 */
import * as gapicConfig from './disks_client_config.json';

const version = require('../../../package.json').version;

/**
 *  The Disks API.
 * @class
 * @memberof v1
 */
export class DisksClient {
  private _terminated = false;
  private _opts: ClientOptions;
  private _gaxModule: typeof gax | typeof gax.fallback;
  private _gaxGrpc: gax.GrpcClient | gax.fallback.GrpcClient;
  private _protos: {};
  private _defaults: {[method: string]: gax.CallSettings};
  auth: gax.GoogleAuth;
  descriptors: Descriptors = {
    page: {},
    stream: {},
    longrunning: {},
    batching: {},
  };
  innerApiCalls: {[name: string]: Function};
  disksStub?: Promise<{[name: string]: Function}>;

  /**
   * Construct an instance of DisksClient.
   *
   * @param {object} [options] - The configuration object.
   * The options accepted by the constructor are described in detail
   * in [this document](https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#creating-the-client-instance).
   * The common options are:
   * @param {object} [options.credentials] - Credentials object.
   * @param {string} [options.credentials.client_email]
   * @param {string} [options.credentials.private_key]
   * @param {string} [options.email] - Account email address. Required when
   *     using a .pem or .p12 keyFilename.
   * @param {string} [options.keyFilename] - Full path to the a .json, .pem, or
   *     .p12 key downloaded from the Google Developers Console. If you provide
   *     a path to a JSON file, the projectId option below is not necessary.
   *     NOTE: .pem and .p12 require you to specify options.email as well.
   * @param {number} [options.port] - The port on which to connect to
   *     the remote host.
   * @param {string} [options.projectId] - The project ID from the Google
   *     Developer's Console, e.g. 'grape-spaceship-123'. We will also check
   *     the environment variable GCLOUD_PROJECT for your project ID. If your
   *     app is running in an environment which supports
   *     {@link https://developers.google.com/identity/protocols/application-default-credentials Application Default Credentials},
   *     your project ID will be detected automatically.
   * @param {string} [options.apiEndpoint] - The domain name of the
   *     API remote host.
   * @param {gax.ClientConfig} [options.clientConfig] - Client configuration override.
   *     Follows the structure of {@link gapicConfig}.
   * @param {boolean} [options.fallback] - Use HTTP fallback mode.
   *     In fallback mode, a special browser-compatible transport implementation is used
   *     instead of gRPC transport. In browser context (if the `window` object is defined)
   *     the fallback mode is enabled automatically; set `options.fallback` to `false`
   *     if you need to override this behavior.
   */
  constructor(opts?: ClientOptions) {
    // Ensure that options include all the required fields.
    const staticMembers = this.constructor as typeof DisksClient;
    const servicePath =
      opts?.servicePath || opts?.apiEndpoint || staticMembers.servicePath;
    const port = opts?.port || staticMembers.port;
    const clientConfig = opts?.clientConfig ?? {};
    const fallback =
      opts?.fallback ??
      (typeof window !== 'undefined' && typeof window?.fetch === 'function');
    opts = Object.assign({servicePath, port, clientConfig, fallback}, opts);

    // If scopes are unset in options and we're connecting to a non-default endpoint, set scopes just in case.
    if (servicePath !== staticMembers.servicePath && !('scopes' in opts)) {
      opts['scopes'] = staticMembers.scopes;
    }

    // Choose either gRPC or proto-over-HTTP implementation of google-gax.
    this._gaxModule = opts.fallback ? gax.fallback : gax;

    // Create a `gaxGrpc` object, with any grpc-specific options sent to the client.
    this._gaxGrpc = new this._gaxModule.GrpcClient(opts);

    // Save options to use in initialize() method.
    this._opts = opts;

    // Save the auth object to the client, for use by other methods.
    this.auth = this._gaxGrpc.auth as gax.GoogleAuth;

    // Set the default scopes in auth client if needed.
    if (servicePath === staticMembers.servicePath) {
      this.auth.defaultScopes = staticMembers.scopes;
    }

    // Determine the client header string.
    const clientHeader = [`gax/${this._gaxModule.version}`, `gapic/${version}`];
    if (typeof process !== 'undefined' && 'versions' in process) {
      clientHeader.push(`gl-node/${process.versions.node}`);
    } else {
      clientHeader.push(`gl-web/${this._gaxModule.version}`);
    }
    if (!opts.fallback) {
      clientHeader.push(`grpc/${this._gaxGrpc.grpcVersion}`);
    }
    if (opts.libName && opts.libVersion) {
      clientHeader.push(`${opts.libName}/${opts.libVersion}`);
    }
    // Load the applicable protos.
    // For Node.js, pass the path to JSON proto file.
    // For browsers, pass the JSON content.

    const nodejsProtoPath = path.join(
      __dirname,
      '..',
      '..',
      'protos',
      'protos.json'
    );
    this._protos = this._gaxGrpc.loadProto(
      opts.fallback
        ? // eslint-disable-next-line @typescript-eslint/no-var-requires
          require('../../protos/protos.json')
        : nodejsProtoPath
    );

    // Put together the default options sent with requests.
    this._defaults = this._gaxGrpc.constructSettings(
      'google.cloud.compute.v1.Disks',
      gapicConfig as gax.ClientConfig,
      opts.clientConfig || {},
      {'x-goog-api-client': clientHeader.join(' ')}
    );

    // Set up a dictionary of "inner API calls"; the core implementation
    // of calling the API is handled in `google-gax`, with this code
    // merely providing the destination and request information.
    this.innerApiCalls = {};
  }

  /**
   * Initialize the client.
   * Performs asynchronous operations (such as authentication) and prepares the client.
   * This function will be called automatically when any class method is called for the
   * first time, but if you need to initialize it before calling an actual method,
   * feel free to call initialize() directly.
   *
   * You can await on this method if you want to make sure the client is initialized.
   *
   * @returns {Promise} A promise that resolves to an authenticated service stub.
   */
  initialize() {
    // If the client stub promise is already initialized, return immediately.
    if (this.disksStub) {
      return this.disksStub;
    }

    // Put together the "service stub" for
    // google.cloud.compute.v1.Disks.
    this.disksStub = this._gaxGrpc.createStub(
      this._opts.fallback
        ? (this._protos as protobuf.Root).lookupService(
            'google.cloud.compute.v1.Disks'
          )
        : // eslint-disable-next-line @typescript-eslint/no-explicit-any
          (this._protos as any).google.cloud.compute.v1.Disks,
      this._opts
    ) as Promise<{[method: string]: Function}>;

    // Iterate over each of the methods that the service provides
    // and create an API call method for each.
    const disksStubMethods = [
      'addResourcePolicies',
      'aggregatedList',
      'createSnapshot',
      'delete',
      'get',
      'getIamPolicy',
      'insert',
      'list',
      'removeResourcePolicies',
      'resize',
      'setIamPolicy',
      'setLabels',
      'testIamPermissions',
    ];
    for (const methodName of disksStubMethods) {
      const callPromise = this.disksStub.then(
        stub => (...args: Array<{}>) => {
          if (this._terminated) {
            return Promise.reject('The client has already been closed.');
          }
          const func = stub[methodName];
          return func.apply(stub, args);
        },
        (err: Error | null | undefined) => () => {
          throw err;
        }
      );

      const descriptor = undefined;
      const apiCall = this._gaxModule.createApiCall(
        callPromise,
        this._defaults[methodName],
        descriptor
      );

      this.innerApiCalls[methodName] = apiCall;
    }

    return this.disksStub;
  }

  /**
   * The DNS address for this API service.
   * @returns {string} The DNS address for this service.
   */
  static get servicePath() {
    return 'compute.googleapis.com';
  }

  /**
   * The DNS address for this API service - same as servicePath(),
   * exists for compatibility reasons.
   * @returns {string} The DNS address for this service.
   */
  static get apiEndpoint() {
    return 'compute.googleapis.com';
  }

  /**
   * The port for this API service.
   * @returns {number} The default port for this service.
   */
  static get port() {
    return 443;
  }

  /**
   * The scopes needed to make gRPC calls for every method defined
   * in this service.
   * @returns {string[]} List of default scopes.
   */
  static get scopes() {
    return [
      'https://www.googleapis.com/auth/compute',
      'https://www.googleapis.com/auth/cloud-platform',
    ];
  }

  getProjectId(): Promise<string>;
  getProjectId(callback: Callback<string, undefined, undefined>): void;
  /**
   * Return the project ID used by this class.
   * @returns {Promise} A promise that resolves to string containing the project ID.
   */
  getProjectId(
    callback?: Callback<string, undefined, undefined>
  ): Promise<string> | void {
    if (callback) {
      this.auth.getProjectId(callback);
      return;
    }
    return this.auth.getProjectId();
  }

  // -------------------
  // -- Service calls --
  // -------------------
  addResourcePolicies(
    request: protos.google.cloud.compute.v1.IAddResourcePoliciesDiskRequest,
    options?: CallOptions
  ): Promise<
    [
      protos.google.cloud.compute.v1.IOperation,
      (
        | protos.google.cloud.compute.v1.IAddResourcePoliciesDiskRequest
        | undefined
      ),
      {} | undefined
    ]
  >;
  addResourcePolicies(
    request: protos.google.cloud.compute.v1.IAddResourcePoliciesDiskRequest,
    options: CallOptions,
    callback: Callback<
      protos.google.cloud.compute.v1.IOperation,
      | protos.google.cloud.compute.v1.IAddResourcePoliciesDiskRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): void;
  addResourcePolicies(
    request: protos.google.cloud.compute.v1.IAddResourcePoliciesDiskRequest,
    callback: Callback<
      protos.google.cloud.compute.v1.IOperation,
      | protos.google.cloud.compute.v1.IAddResourcePoliciesDiskRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): void;
  /**
   * Adds existing resource policies to a disk. You can only add one policy which will be applied to this disk for scheduling snapshot creation.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.disk
   *   The disk name for this request.
   * @param {google.cloud.compute.v1.DisksAddResourcePoliciesRequest} request.disksAddResourcePoliciesRequestResource
   *   The body resource for this request
   * @param {string} request.project
   *   Project ID for this request.
   * @param {string} request.requestId
   *   An optional request ID to identify requests. Specify a unique request ID so that if you must retry your request, the server will know to ignore the request if it has already been completed.
   *
   *   For example, consider a situation where you make an initial request and the request times out. If you make the request again with the same request ID, the server can check if original operation with the same request ID was received, and if so, will ignore the second request. This prevents clients from accidentally creating duplicate commitments.
   *
   *   The request ID must be a valid UUID with the exception that zero UUID is not supported (00000000-0000-0000-0000-000000000000).
   * @param {string} request.zone
   *   The name of the zone for this request.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing [Operation]{@link google.cloud.compute.v1.Operation}.
   *   Please see the
   *   [documentation](https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods)
   *   for more details and examples.
   * @example
   * const [response] = await client.addResourcePolicies(request);
   */
  addResourcePolicies(
    request: protos.google.cloud.compute.v1.IAddResourcePoliciesDiskRequest,
    optionsOrCallback?:
      | CallOptions
      | Callback<
          protos.google.cloud.compute.v1.IOperation,
          | protos.google.cloud.compute.v1.IAddResourcePoliciesDiskRequest
          | null
          | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      protos.google.cloud.compute.v1.IOperation,
      | protos.google.cloud.compute.v1.IAddResourcePoliciesDiskRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): Promise<
    [
      protos.google.cloud.compute.v1.IOperation,
      (
        | protos.google.cloud.compute.v1.IAddResourcePoliciesDiskRequest
        | undefined
      ),
      {} | undefined
    ]
  > | void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      project: request.project || '',
    });
    this.initialize();
    return this.innerApiCalls.addResourcePolicies(request, options, callback);
  }
  aggregatedList(
    request: protos.google.cloud.compute.v1.IAggregatedListDisksRequest,
    options?: CallOptions
  ): Promise<
    [
      protos.google.cloud.compute.v1.IDiskAggregatedList,
      protos.google.cloud.compute.v1.IAggregatedListDisksRequest | undefined,
      {} | undefined
    ]
  >;
  aggregatedList(
    request: protos.google.cloud.compute.v1.IAggregatedListDisksRequest,
    options: CallOptions,
    callback: Callback<
      protos.google.cloud.compute.v1.IDiskAggregatedList,
      | protos.google.cloud.compute.v1.IAggregatedListDisksRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): void;
  aggregatedList(
    request: protos.google.cloud.compute.v1.IAggregatedListDisksRequest,
    callback: Callback<
      protos.google.cloud.compute.v1.IDiskAggregatedList,
      | protos.google.cloud.compute.v1.IAggregatedListDisksRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): void;
  /**
   * Retrieves an aggregated list of persistent disks.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.filter
   *   A filter expression that filters resources listed in the response. The expression must specify the field name, a comparison operator, and the value that you want to use for filtering. The value must be a string, a number, or a boolean. The comparison operator must be either `=`, `!=`, `>`, or `<`.
   *
   *   For example, if you are filtering Compute Engine instances, you can exclude instances named `example-instance` by specifying `name != example-instance`.
   *
   *   You can also filter nested fields. For example, you could specify `scheduling.automaticRestart = false` to include instances only if they are not scheduled for automatic restarts. You can use filtering on nested fields to filter based on resource labels.
   *
   *   To filter on multiple expressions, provide each separate expression within parentheses. For example: ``` (scheduling.automaticRestart = true) (cpuPlatform = "Intel Skylake") ``` By default, each expression is an `AND` expression. However, you can include `AND` and `OR` expressions explicitly. For example: ``` (cpuPlatform = "Intel Skylake") OR (cpuPlatform = "Intel Broadwell") AND (scheduling.automaticRestart = true) ```
   * @param {boolean} request.includeAllScopes
   *   Indicates whether every visible scope for each scope type (zone, region, global) should be included in the response. For new resource types added after this field, the flag has no effect as new resource types will always include every visible scope for each scope type in response. For resource types which predate this field, if this flag is omitted or false, only scopes of the scope types where the resource type is expected to be found will be included.
   * @param {number} request.maxResults
   *   The maximum number of results per page that should be returned. If the number of available results is larger than `maxResults`, Compute Engine returns a `nextPageToken` that can be used to get the next page of results in subsequent list requests. Acceptable values are `0` to `500`, inclusive. (Default: `500`)
   * @param {string} request.orderBy
   *   Sorts list results by a certain order. By default, results are returned in alphanumerical order based on the resource name.
   *
   *   You can also sort results in descending order based on the creation timestamp using `orderBy="creationTimestamp desc"`. This sorts results based on the `creationTimestamp` field in reverse chronological order (newest result first). Use this to sort resources like operations so that the newest operation is returned first.
   *
   *   Currently, only sorting by `name` or `creationTimestamp desc` is supported.
   * @param {string} request.pageToken
   *   Specifies a page token to use. Set `pageToken` to the `nextPageToken` returned by a previous list request to get the next page of results.
   * @param {string} request.project
   *   Project ID for this request.
   * @param {boolean} request.returnPartialSuccess
   *   Opt-in for partial success behavior which provides partial results in case of failure. The default value is false and the logic is the same as today.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing [DiskAggregatedList]{@link google.cloud.compute.v1.DiskAggregatedList}.
   *   Please see the
   *   [documentation](https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods)
   *   for more details and examples.
   * @example
   * const [response] = await client.aggregatedList(request);
   */
  aggregatedList(
    request: protos.google.cloud.compute.v1.IAggregatedListDisksRequest,
    optionsOrCallback?:
      | CallOptions
      | Callback<
          protos.google.cloud.compute.v1.IDiskAggregatedList,
          | protos.google.cloud.compute.v1.IAggregatedListDisksRequest
          | null
          | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      protos.google.cloud.compute.v1.IDiskAggregatedList,
      | protos.google.cloud.compute.v1.IAggregatedListDisksRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): Promise<
    [
      protos.google.cloud.compute.v1.IDiskAggregatedList,
      protos.google.cloud.compute.v1.IAggregatedListDisksRequest | undefined,
      {} | undefined
    ]
  > | void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      project: request.project || '',
    });
    this.initialize();
    return this.innerApiCalls.aggregatedList(request, options, callback);
  }
  createSnapshot(
    request: protos.google.cloud.compute.v1.ICreateSnapshotDiskRequest,
    options?: CallOptions
  ): Promise<
    [
      protos.google.cloud.compute.v1.IOperation,
      protos.google.cloud.compute.v1.ICreateSnapshotDiskRequest | undefined,
      {} | undefined
    ]
  >;
  createSnapshot(
    request: protos.google.cloud.compute.v1.ICreateSnapshotDiskRequest,
    options: CallOptions,
    callback: Callback<
      protos.google.cloud.compute.v1.IOperation,
      | protos.google.cloud.compute.v1.ICreateSnapshotDiskRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): void;
  createSnapshot(
    request: protos.google.cloud.compute.v1.ICreateSnapshotDiskRequest,
    callback: Callback<
      protos.google.cloud.compute.v1.IOperation,
      | protos.google.cloud.compute.v1.ICreateSnapshotDiskRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): void;
  /**
   * Creates a snapshot of a specified persistent disk.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.disk
   *   Name of the persistent disk to snapshot.
   * @param {boolean} request.guestFlush
   *   [Input Only] Whether to attempt an application consistent snapshot by informing the OS to prepare for the snapshot process. Currently only supported on Windows instances using the Volume Shadow Copy Service (VSS).
   * @param {string} request.project
   *   Project ID for this request.
   * @param {string} request.requestId
   *   An optional request ID to identify requests. Specify a unique request ID so that if you must retry your request, the server will know to ignore the request if it has already been completed.
   *
   *   For example, consider a situation where you make an initial request and the request times out. If you make the request again with the same request ID, the server can check if original operation with the same request ID was received, and if so, will ignore the second request. This prevents clients from accidentally creating duplicate commitments.
   *
   *   The request ID must be a valid UUID with the exception that zero UUID is not supported (00000000-0000-0000-0000-000000000000).
   * @param {google.cloud.compute.v1.Snapshot} request.snapshotResource
   *   The body resource for this request
   * @param {string} request.zone
   *   The name of the zone for this request.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing [Operation]{@link google.cloud.compute.v1.Operation}.
   *   Please see the
   *   [documentation](https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods)
   *   for more details and examples.
   * @example
   * const [response] = await client.createSnapshot(request);
   */
  createSnapshot(
    request: protos.google.cloud.compute.v1.ICreateSnapshotDiskRequest,
    optionsOrCallback?:
      | CallOptions
      | Callback<
          protos.google.cloud.compute.v1.IOperation,
          | protos.google.cloud.compute.v1.ICreateSnapshotDiskRequest
          | null
          | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      protos.google.cloud.compute.v1.IOperation,
      | protos.google.cloud.compute.v1.ICreateSnapshotDiskRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): Promise<
    [
      protos.google.cloud.compute.v1.IOperation,
      protos.google.cloud.compute.v1.ICreateSnapshotDiskRequest | undefined,
      {} | undefined
    ]
  > | void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      project: request.project || '',
    });
    this.initialize();
    return this.innerApiCalls.createSnapshot(request, options, callback);
  }
  delete(
    request: protos.google.cloud.compute.v1.IDeleteDiskRequest,
    options?: CallOptions
  ): Promise<
    [
      protos.google.cloud.compute.v1.IOperation,
      protos.google.cloud.compute.v1.IDeleteDiskRequest | undefined,
      {} | undefined
    ]
  >;
  delete(
    request: protos.google.cloud.compute.v1.IDeleteDiskRequest,
    options: CallOptions,
    callback: Callback<
      protos.google.cloud.compute.v1.IOperation,
      protos.google.cloud.compute.v1.IDeleteDiskRequest | null | undefined,
      {} | null | undefined
    >
  ): void;
  delete(
    request: protos.google.cloud.compute.v1.IDeleteDiskRequest,
    callback: Callback<
      protos.google.cloud.compute.v1.IOperation,
      protos.google.cloud.compute.v1.IDeleteDiskRequest | null | undefined,
      {} | null | undefined
    >
  ): void;
  /**
   * Deletes the specified persistent disk. Deleting a disk removes its data permanently and is irreversible. However, deleting a disk does not delete any snapshots previously made from the disk. You must separately delete snapshots.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.disk
   *   Name of the persistent disk to delete.
   * @param {string} request.project
   *   Project ID for this request.
   * @param {string} request.requestId
   *   An optional request ID to identify requests. Specify a unique request ID so that if you must retry your request, the server will know to ignore the request if it has already been completed.
   *
   *   For example, consider a situation where you make an initial request and the request times out. If you make the request again with the same request ID, the server can check if original operation with the same request ID was received, and if so, will ignore the second request. This prevents clients from accidentally creating duplicate commitments.
   *
   *   The request ID must be a valid UUID with the exception that zero UUID is not supported (00000000-0000-0000-0000-000000000000).
   * @param {string} request.zone
   *   The name of the zone for this request.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing [Operation]{@link google.cloud.compute.v1.Operation}.
   *   Please see the
   *   [documentation](https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods)
   *   for more details and examples.
   * @example
   * const [response] = await client.delete(request);
   */
  delete(
    request: protos.google.cloud.compute.v1.IDeleteDiskRequest,
    optionsOrCallback?:
      | CallOptions
      | Callback<
          protos.google.cloud.compute.v1.IOperation,
          protos.google.cloud.compute.v1.IDeleteDiskRequest | null | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      protos.google.cloud.compute.v1.IOperation,
      protos.google.cloud.compute.v1.IDeleteDiskRequest | null | undefined,
      {} | null | undefined
    >
  ): Promise<
    [
      protos.google.cloud.compute.v1.IOperation,
      protos.google.cloud.compute.v1.IDeleteDiskRequest | undefined,
      {} | undefined
    ]
  > | void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      project: request.project || '',
    });
    this.initialize();
    return this.innerApiCalls.delete(request, options, callback);
  }
  get(
    request: protos.google.cloud.compute.v1.IGetDiskRequest,
    options?: CallOptions
  ): Promise<
    [
      protos.google.cloud.compute.v1.IDisk,
      protos.google.cloud.compute.v1.IGetDiskRequest | undefined,
      {} | undefined
    ]
  >;
  get(
    request: protos.google.cloud.compute.v1.IGetDiskRequest,
    options: CallOptions,
    callback: Callback<
      protos.google.cloud.compute.v1.IDisk,
      protos.google.cloud.compute.v1.IGetDiskRequest | null | undefined,
      {} | null | undefined
    >
  ): void;
  get(
    request: protos.google.cloud.compute.v1.IGetDiskRequest,
    callback: Callback<
      protos.google.cloud.compute.v1.IDisk,
      protos.google.cloud.compute.v1.IGetDiskRequest | null | undefined,
      {} | null | undefined
    >
  ): void;
  /**
   * Returns a specified persistent disk. Gets a list of available persistent disks by making a list() request.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.disk
   *   Name of the persistent disk to return.
   * @param {string} request.project
   *   Project ID for this request.
   * @param {string} request.zone
   *   The name of the zone for this request.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing [Disk]{@link google.cloud.compute.v1.Disk}.
   *   Please see the
   *   [documentation](https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods)
   *   for more details and examples.
   * @example
   * const [response] = await client.get(request);
   */
  get(
    request: protos.google.cloud.compute.v1.IGetDiskRequest,
    optionsOrCallback?:
      | CallOptions
      | Callback<
          protos.google.cloud.compute.v1.IDisk,
          protos.google.cloud.compute.v1.IGetDiskRequest | null | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      protos.google.cloud.compute.v1.IDisk,
      protos.google.cloud.compute.v1.IGetDiskRequest | null | undefined,
      {} | null | undefined
    >
  ): Promise<
    [
      protos.google.cloud.compute.v1.IDisk,
      protos.google.cloud.compute.v1.IGetDiskRequest | undefined,
      {} | undefined
    ]
  > | void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      project: request.project || '',
    });
    this.initialize();
    return this.innerApiCalls.get(request, options, callback);
  }
  getIamPolicy(
    request: protos.google.cloud.compute.v1.IGetIamPolicyDiskRequest,
    options?: CallOptions
  ): Promise<
    [
      protos.google.cloud.compute.v1.IPolicy,
      protos.google.cloud.compute.v1.IGetIamPolicyDiskRequest | undefined,
      {} | undefined
    ]
  >;
  getIamPolicy(
    request: protos.google.cloud.compute.v1.IGetIamPolicyDiskRequest,
    options: CallOptions,
    callback: Callback<
      protos.google.cloud.compute.v1.IPolicy,
      | protos.google.cloud.compute.v1.IGetIamPolicyDiskRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): void;
  getIamPolicy(
    request: protos.google.cloud.compute.v1.IGetIamPolicyDiskRequest,
    callback: Callback<
      protos.google.cloud.compute.v1.IPolicy,
      | protos.google.cloud.compute.v1.IGetIamPolicyDiskRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): void;
  /**
   * Gets the access control policy for a resource. May be empty if no such policy or resource exists.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {number} request.optionsRequestedPolicyVersion
   *   Requested IAM Policy version.
   * @param {string} request.project
   *   Project ID for this request.
   * @param {string} request.resource
   *   Name or id of the resource for this request.
   * @param {string} request.zone
   *   The name of the zone for this request.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing [Policy]{@link google.cloud.compute.v1.Policy}.
   *   Please see the
   *   [documentation](https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods)
   *   for more details and examples.
   * @example
   * const [response] = await client.getIamPolicy(request);
   */
  getIamPolicy(
    request: protos.google.cloud.compute.v1.IGetIamPolicyDiskRequest,
    optionsOrCallback?:
      | CallOptions
      | Callback<
          protos.google.cloud.compute.v1.IPolicy,
          | protos.google.cloud.compute.v1.IGetIamPolicyDiskRequest
          | null
          | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      protos.google.cloud.compute.v1.IPolicy,
      | protos.google.cloud.compute.v1.IGetIamPolicyDiskRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): Promise<
    [
      protos.google.cloud.compute.v1.IPolicy,
      protos.google.cloud.compute.v1.IGetIamPolicyDiskRequest | undefined,
      {} | undefined
    ]
  > | void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      project: request.project || '',
    });
    this.initialize();
    return this.innerApiCalls.getIamPolicy(request, options, callback);
  }
  insert(
    request: protos.google.cloud.compute.v1.IInsertDiskRequest,
    options?: CallOptions
  ): Promise<
    [
      protos.google.cloud.compute.v1.IOperation,
      protos.google.cloud.compute.v1.IInsertDiskRequest | undefined,
      {} | undefined
    ]
  >;
  insert(
    request: protos.google.cloud.compute.v1.IInsertDiskRequest,
    options: CallOptions,
    callback: Callback<
      protos.google.cloud.compute.v1.IOperation,
      protos.google.cloud.compute.v1.IInsertDiskRequest | null | undefined,
      {} | null | undefined
    >
  ): void;
  insert(
    request: protos.google.cloud.compute.v1.IInsertDiskRequest,
    callback: Callback<
      protos.google.cloud.compute.v1.IOperation,
      protos.google.cloud.compute.v1.IInsertDiskRequest | null | undefined,
      {} | null | undefined
    >
  ): void;
  /**
   * Creates a persistent disk in the specified project using the data in the request. You can create a disk from a source (sourceImage, sourceSnapshot, or sourceDisk) or create an empty 500 GB data disk by omitting all properties. You can also create a disk that is larger than the default size by specifying the sizeGb property.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {google.cloud.compute.v1.Disk} request.diskResource
   *   The body resource for this request
   * @param {string} request.project
   *   Project ID for this request.
   * @param {string} request.requestId
   *   An optional request ID to identify requests. Specify a unique request ID so that if you must retry your request, the server will know to ignore the request if it has already been completed.
   *
   *   For example, consider a situation where you make an initial request and the request times out. If you make the request again with the same request ID, the server can check if original operation with the same request ID was received, and if so, will ignore the second request. This prevents clients from accidentally creating duplicate commitments.
   *
   *   The request ID must be a valid UUID with the exception that zero UUID is not supported (00000000-0000-0000-0000-000000000000).
   * @param {string} request.sourceImage
   *   Optional. Source image to restore onto a disk.
   * @param {string} request.zone
   *   The name of the zone for this request.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing [Operation]{@link google.cloud.compute.v1.Operation}.
   *   Please see the
   *   [documentation](https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods)
   *   for more details and examples.
   * @example
   * const [response] = await client.insert(request);
   */
  insert(
    request: protos.google.cloud.compute.v1.IInsertDiskRequest,
    optionsOrCallback?:
      | CallOptions
      | Callback<
          protos.google.cloud.compute.v1.IOperation,
          protos.google.cloud.compute.v1.IInsertDiskRequest | null | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      protos.google.cloud.compute.v1.IOperation,
      protos.google.cloud.compute.v1.IInsertDiskRequest | null | undefined,
      {} | null | undefined
    >
  ): Promise<
    [
      protos.google.cloud.compute.v1.IOperation,
      protos.google.cloud.compute.v1.IInsertDiskRequest | undefined,
      {} | undefined
    ]
  > | void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      project: request.project || '',
    });
    this.initialize();
    return this.innerApiCalls.insert(request, options, callback);
  }
  list(
    request: protos.google.cloud.compute.v1.IListDisksRequest,
    options?: CallOptions
  ): Promise<
    [
      protos.google.cloud.compute.v1.IDiskList,
      protos.google.cloud.compute.v1.IListDisksRequest | undefined,
      {} | undefined
    ]
  >;
  list(
    request: protos.google.cloud.compute.v1.IListDisksRequest,
    options: CallOptions,
    callback: Callback<
      protos.google.cloud.compute.v1.IDiskList,
      protos.google.cloud.compute.v1.IListDisksRequest | null | undefined,
      {} | null | undefined
    >
  ): void;
  list(
    request: protos.google.cloud.compute.v1.IListDisksRequest,
    callback: Callback<
      protos.google.cloud.compute.v1.IDiskList,
      protos.google.cloud.compute.v1.IListDisksRequest | null | undefined,
      {} | null | undefined
    >
  ): void;
  /**
   * Retrieves a list of persistent disks contained within the specified zone.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.filter
   *   A filter expression that filters resources listed in the response. The expression must specify the field name, a comparison operator, and the value that you want to use for filtering. The value must be a string, a number, or a boolean. The comparison operator must be either `=`, `!=`, `>`, or `<`.
   *
   *   For example, if you are filtering Compute Engine instances, you can exclude instances named `example-instance` by specifying `name != example-instance`.
   *
   *   You can also filter nested fields. For example, you could specify `scheduling.automaticRestart = false` to include instances only if they are not scheduled for automatic restarts. You can use filtering on nested fields to filter based on resource labels.
   *
   *   To filter on multiple expressions, provide each separate expression within parentheses. For example: ``` (scheduling.automaticRestart = true) (cpuPlatform = "Intel Skylake") ``` By default, each expression is an `AND` expression. However, you can include `AND` and `OR` expressions explicitly. For example: ``` (cpuPlatform = "Intel Skylake") OR (cpuPlatform = "Intel Broadwell") AND (scheduling.automaticRestart = true) ```
   * @param {number} request.maxResults
   *   The maximum number of results per page that should be returned. If the number of available results is larger than `maxResults`, Compute Engine returns a `nextPageToken` that can be used to get the next page of results in subsequent list requests. Acceptable values are `0` to `500`, inclusive. (Default: `500`)
   * @param {string} request.orderBy
   *   Sorts list results by a certain order. By default, results are returned in alphanumerical order based on the resource name.
   *
   *   You can also sort results in descending order based on the creation timestamp using `orderBy="creationTimestamp desc"`. This sorts results based on the `creationTimestamp` field in reverse chronological order (newest result first). Use this to sort resources like operations so that the newest operation is returned first.
   *
   *   Currently, only sorting by `name` or `creationTimestamp desc` is supported.
   * @param {string} request.pageToken
   *   Specifies a page token to use. Set `pageToken` to the `nextPageToken` returned by a previous list request to get the next page of results.
   * @param {string} request.project
   *   Project ID for this request.
   * @param {boolean} request.returnPartialSuccess
   *   Opt-in for partial success behavior which provides partial results in case of failure. The default value is false and the logic is the same as today.
   * @param {string} request.zone
   *   The name of the zone for this request.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing [DiskList]{@link google.cloud.compute.v1.DiskList}.
   *   Please see the
   *   [documentation](https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods)
   *   for more details and examples.
   * @example
   * const [response] = await client.list(request);
   */
  list(
    request: protos.google.cloud.compute.v1.IListDisksRequest,
    optionsOrCallback?:
      | CallOptions
      | Callback<
          protos.google.cloud.compute.v1.IDiskList,
          protos.google.cloud.compute.v1.IListDisksRequest | null | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      protos.google.cloud.compute.v1.IDiskList,
      protos.google.cloud.compute.v1.IListDisksRequest | null | undefined,
      {} | null | undefined
    >
  ): Promise<
    [
      protos.google.cloud.compute.v1.IDiskList,
      protos.google.cloud.compute.v1.IListDisksRequest | undefined,
      {} | undefined
    ]
  > | void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      project: request.project || '',
    });
    this.initialize();
    return this.innerApiCalls.list(request, options, callback);
  }
  removeResourcePolicies(
    request: protos.google.cloud.compute.v1.IRemoveResourcePoliciesDiskRequest,
    options?: CallOptions
  ): Promise<
    [
      protos.google.cloud.compute.v1.IOperation,
      (
        | protos.google.cloud.compute.v1.IRemoveResourcePoliciesDiskRequest
        | undefined
      ),
      {} | undefined
    ]
  >;
  removeResourcePolicies(
    request: protos.google.cloud.compute.v1.IRemoveResourcePoliciesDiskRequest,
    options: CallOptions,
    callback: Callback<
      protos.google.cloud.compute.v1.IOperation,
      | protos.google.cloud.compute.v1.IRemoveResourcePoliciesDiskRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): void;
  removeResourcePolicies(
    request: protos.google.cloud.compute.v1.IRemoveResourcePoliciesDiskRequest,
    callback: Callback<
      protos.google.cloud.compute.v1.IOperation,
      | protos.google.cloud.compute.v1.IRemoveResourcePoliciesDiskRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): void;
  /**
   * Removes resource policies from a disk.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.disk
   *   The disk name for this request.
   * @param {google.cloud.compute.v1.DisksRemoveResourcePoliciesRequest} request.disksRemoveResourcePoliciesRequestResource
   *   The body resource for this request
   * @param {string} request.project
   *   Project ID for this request.
   * @param {string} request.requestId
   *   An optional request ID to identify requests. Specify a unique request ID so that if you must retry your request, the server will know to ignore the request if it has already been completed.
   *
   *   For example, consider a situation where you make an initial request and the request times out. If you make the request again with the same request ID, the server can check if original operation with the same request ID was received, and if so, will ignore the second request. This prevents clients from accidentally creating duplicate commitments.
   *
   *   The request ID must be a valid UUID with the exception that zero UUID is not supported (00000000-0000-0000-0000-000000000000).
   * @param {string} request.zone
   *   The name of the zone for this request.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing [Operation]{@link google.cloud.compute.v1.Operation}.
   *   Please see the
   *   [documentation](https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods)
   *   for more details and examples.
   * @example
   * const [response] = await client.removeResourcePolicies(request);
   */
  removeResourcePolicies(
    request: protos.google.cloud.compute.v1.IRemoveResourcePoliciesDiskRequest,
    optionsOrCallback?:
      | CallOptions
      | Callback<
          protos.google.cloud.compute.v1.IOperation,
          | protos.google.cloud.compute.v1.IRemoveResourcePoliciesDiskRequest
          | null
          | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      protos.google.cloud.compute.v1.IOperation,
      | protos.google.cloud.compute.v1.IRemoveResourcePoliciesDiskRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): Promise<
    [
      protos.google.cloud.compute.v1.IOperation,
      (
        | protos.google.cloud.compute.v1.IRemoveResourcePoliciesDiskRequest
        | undefined
      ),
      {} | undefined
    ]
  > | void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      project: request.project || '',
    });
    this.initialize();
    return this.innerApiCalls.removeResourcePolicies(
      request,
      options,
      callback
    );
  }
  resize(
    request: protos.google.cloud.compute.v1.IResizeDiskRequest,
    options?: CallOptions
  ): Promise<
    [
      protos.google.cloud.compute.v1.IOperation,
      protos.google.cloud.compute.v1.IResizeDiskRequest | undefined,
      {} | undefined
    ]
  >;
  resize(
    request: protos.google.cloud.compute.v1.IResizeDiskRequest,
    options: CallOptions,
    callback: Callback<
      protos.google.cloud.compute.v1.IOperation,
      protos.google.cloud.compute.v1.IResizeDiskRequest | null | undefined,
      {} | null | undefined
    >
  ): void;
  resize(
    request: protos.google.cloud.compute.v1.IResizeDiskRequest,
    callback: Callback<
      protos.google.cloud.compute.v1.IOperation,
      protos.google.cloud.compute.v1.IResizeDiskRequest | null | undefined,
      {} | null | undefined
    >
  ): void;
  /**
   * Resizes the specified persistent disk. You can only increase the size of the disk.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.disk
   *   The name of the persistent disk.
   * @param {google.cloud.compute.v1.DisksResizeRequest} request.disksResizeRequestResource
   *   The body resource for this request
   * @param {string} request.project
   *   Project ID for this request.
   * @param {string} request.requestId
   *   An optional request ID to identify requests. Specify a unique request ID so that if you must retry your request, the server will know to ignore the request if it has already been completed.
   *
   *   For example, consider a situation where you make an initial request and the request times out. If you make the request again with the same request ID, the server can check if original operation with the same request ID was received, and if so, will ignore the second request. This prevents clients from accidentally creating duplicate commitments.
   *
   *   The request ID must be a valid UUID with the exception that zero UUID is not supported (00000000-0000-0000-0000-000000000000).
   * @param {string} request.zone
   *   The name of the zone for this request.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing [Operation]{@link google.cloud.compute.v1.Operation}.
   *   Please see the
   *   [documentation](https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods)
   *   for more details and examples.
   * @example
   * const [response] = await client.resize(request);
   */
  resize(
    request: protos.google.cloud.compute.v1.IResizeDiskRequest,
    optionsOrCallback?:
      | CallOptions
      | Callback<
          protos.google.cloud.compute.v1.IOperation,
          protos.google.cloud.compute.v1.IResizeDiskRequest | null | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      protos.google.cloud.compute.v1.IOperation,
      protos.google.cloud.compute.v1.IResizeDiskRequest | null | undefined,
      {} | null | undefined
    >
  ): Promise<
    [
      protos.google.cloud.compute.v1.IOperation,
      protos.google.cloud.compute.v1.IResizeDiskRequest | undefined,
      {} | undefined
    ]
  > | void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      project: request.project || '',
    });
    this.initialize();
    return this.innerApiCalls.resize(request, options, callback);
  }
  setIamPolicy(
    request: protos.google.cloud.compute.v1.ISetIamPolicyDiskRequest,
    options?: CallOptions
  ): Promise<
    [
      protos.google.cloud.compute.v1.IPolicy,
      protos.google.cloud.compute.v1.ISetIamPolicyDiskRequest | undefined,
      {} | undefined
    ]
  >;
  setIamPolicy(
    request: protos.google.cloud.compute.v1.ISetIamPolicyDiskRequest,
    options: CallOptions,
    callback: Callback<
      protos.google.cloud.compute.v1.IPolicy,
      | protos.google.cloud.compute.v1.ISetIamPolicyDiskRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): void;
  setIamPolicy(
    request: protos.google.cloud.compute.v1.ISetIamPolicyDiskRequest,
    callback: Callback<
      protos.google.cloud.compute.v1.IPolicy,
      | protos.google.cloud.compute.v1.ISetIamPolicyDiskRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): void;
  /**
   * Sets the access control policy on the specified resource. Replaces any existing policy.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.project
   *   Project ID for this request.
   * @param {string} request.resource
   *   Name or id of the resource for this request.
   * @param {string} request.zone
   *   The name of the zone for this request.
   * @param {google.cloud.compute.v1.ZoneSetPolicyRequest} request.zoneSetPolicyRequestResource
   *   The body resource for this request
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing [Policy]{@link google.cloud.compute.v1.Policy}.
   *   Please see the
   *   [documentation](https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods)
   *   for more details and examples.
   * @example
   * const [response] = await client.setIamPolicy(request);
   */
  setIamPolicy(
    request: protos.google.cloud.compute.v1.ISetIamPolicyDiskRequest,
    optionsOrCallback?:
      | CallOptions
      | Callback<
          protos.google.cloud.compute.v1.IPolicy,
          | protos.google.cloud.compute.v1.ISetIamPolicyDiskRequest
          | null
          | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      protos.google.cloud.compute.v1.IPolicy,
      | protos.google.cloud.compute.v1.ISetIamPolicyDiskRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): Promise<
    [
      protos.google.cloud.compute.v1.IPolicy,
      protos.google.cloud.compute.v1.ISetIamPolicyDiskRequest | undefined,
      {} | undefined
    ]
  > | void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      project: request.project || '',
    });
    this.initialize();
    return this.innerApiCalls.setIamPolicy(request, options, callback);
  }
  setLabels(
    request: protos.google.cloud.compute.v1.ISetLabelsDiskRequest,
    options?: CallOptions
  ): Promise<
    [
      protos.google.cloud.compute.v1.IOperation,
      protos.google.cloud.compute.v1.ISetLabelsDiskRequest | undefined,
      {} | undefined
    ]
  >;
  setLabels(
    request: protos.google.cloud.compute.v1.ISetLabelsDiskRequest,
    options: CallOptions,
    callback: Callback<
      protos.google.cloud.compute.v1.IOperation,
      protos.google.cloud.compute.v1.ISetLabelsDiskRequest | null | undefined,
      {} | null | undefined
    >
  ): void;
  setLabels(
    request: protos.google.cloud.compute.v1.ISetLabelsDiskRequest,
    callback: Callback<
      protos.google.cloud.compute.v1.IOperation,
      protos.google.cloud.compute.v1.ISetLabelsDiskRequest | null | undefined,
      {} | null | undefined
    >
  ): void;
  /**
   * Sets the labels on a disk. To learn more about labels, read the Labeling Resources documentation.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.project
   *   Project ID for this request.
   * @param {string} request.requestId
   *   An optional request ID to identify requests. Specify a unique request ID so that if you must retry your request, the server will know to ignore the request if it has already been completed.
   *
   *   For example, consider a situation where you make an initial request and the request times out. If you make the request again with the same request ID, the server can check if original operation with the same request ID was received, and if so, will ignore the second request. This prevents clients from accidentally creating duplicate commitments.
   *
   *   The request ID must be a valid UUID with the exception that zero UUID is not supported (00000000-0000-0000-0000-000000000000).
   * @param {string} request.resource
   *   Name or id of the resource for this request.
   * @param {string} request.zone
   *   The name of the zone for this request.
   * @param {google.cloud.compute.v1.ZoneSetLabelsRequest} request.zoneSetLabelsRequestResource
   *   The body resource for this request
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing [Operation]{@link google.cloud.compute.v1.Operation}.
   *   Please see the
   *   [documentation](https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods)
   *   for more details and examples.
   * @example
   * const [response] = await client.setLabels(request);
   */
  setLabels(
    request: protos.google.cloud.compute.v1.ISetLabelsDiskRequest,
    optionsOrCallback?:
      | CallOptions
      | Callback<
          protos.google.cloud.compute.v1.IOperation,
          | protos.google.cloud.compute.v1.ISetLabelsDiskRequest
          | null
          | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      protos.google.cloud.compute.v1.IOperation,
      protos.google.cloud.compute.v1.ISetLabelsDiskRequest | null | undefined,
      {} | null | undefined
    >
  ): Promise<
    [
      protos.google.cloud.compute.v1.IOperation,
      protos.google.cloud.compute.v1.ISetLabelsDiskRequest | undefined,
      {} | undefined
    ]
  > | void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      project: request.project || '',
    });
    this.initialize();
    return this.innerApiCalls.setLabels(request, options, callback);
  }
  testIamPermissions(
    request: protos.google.cloud.compute.v1.ITestIamPermissionsDiskRequest,
    options?: CallOptions
  ): Promise<
    [
      protos.google.cloud.compute.v1.ITestPermissionsResponse,
      protos.google.cloud.compute.v1.ITestIamPermissionsDiskRequest | undefined,
      {} | undefined
    ]
  >;
  testIamPermissions(
    request: protos.google.cloud.compute.v1.ITestIamPermissionsDiskRequest,
    options: CallOptions,
    callback: Callback<
      protos.google.cloud.compute.v1.ITestPermissionsResponse,
      | protos.google.cloud.compute.v1.ITestIamPermissionsDiskRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): void;
  testIamPermissions(
    request: protos.google.cloud.compute.v1.ITestIamPermissionsDiskRequest,
    callback: Callback<
      protos.google.cloud.compute.v1.ITestPermissionsResponse,
      | protos.google.cloud.compute.v1.ITestIamPermissionsDiskRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): void;
  /**
   * Returns permissions that a caller has on the specified resource.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.project
   *   Project ID for this request.
   * @param {string} request.resource
   *   Name or id of the resource for this request.
   * @param {google.cloud.compute.v1.TestPermissionsRequest} request.testPermissionsRequestResource
   *   The body resource for this request
   * @param {string} request.zone
   *   The name of the zone for this request.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing [TestPermissionsResponse]{@link google.cloud.compute.v1.TestPermissionsResponse}.
   *   Please see the
   *   [documentation](https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods)
   *   for more details and examples.
   * @example
   * const [response] = await client.testIamPermissions(request);
   */
  testIamPermissions(
    request: protos.google.cloud.compute.v1.ITestIamPermissionsDiskRequest,
    optionsOrCallback?:
      | CallOptions
      | Callback<
          protos.google.cloud.compute.v1.ITestPermissionsResponse,
          | protos.google.cloud.compute.v1.ITestIamPermissionsDiskRequest
          | null
          | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      protos.google.cloud.compute.v1.ITestPermissionsResponse,
      | protos.google.cloud.compute.v1.ITestIamPermissionsDiskRequest
      | null
      | undefined,
      {} | null | undefined
    >
  ): Promise<
    [
      protos.google.cloud.compute.v1.ITestPermissionsResponse,
      protos.google.cloud.compute.v1.ITestIamPermissionsDiskRequest | undefined,
      {} | undefined
    ]
  > | void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      project: request.project || '',
    });
    this.initialize();
    return this.innerApiCalls.testIamPermissions(request, options, callback);
  }

  /**
   * Terminate the gRPC channel and close the client.
   *
   * The client will no longer be usable and all future behavior is undefined.
   * @returns {Promise} A promise that resolves when the client is closed.
   */
  close(): Promise<void> {
    this.initialize();
    if (!this._terminated) {
      return this.disksStub!.then(stub => {
        this._terminated = true;
        stub.close();
      });
    }
    return Promise.resolve();
  }
}
